Repository matter-labs/zksync-sso-clave-contracts, pull requests merged in 2025-01, with the labels that each got.

#230 chore: update variable names
  src/SsoAccount.sol
  src/handlers/ERC1271Handler.sol
  src/libraries/JsmnSolLib.sol
  src/managers/ValidatorManager.sol
  src/validators/SessionKeyValidator.sol
Labels: documentation, good first issue

#235 chore: update comments
  src/handlers/ValidationHandler.sol
  src/libraries/JsmnSolLib.sol
  src/libraries/LinkedList.sol
  src/managers/OwnerManager.sol
Labels: documentation, good first issue, project: contracts

#241 chore: use explicit imports
  src/helpers/TimestampAsserterLocator.sol
  src/helpers/TokenCallbackHandler.sol
Labels: good first issue, project: contracts

#240 chore: adjust constant permissions
  src/handlers/ERC1271Handler.sol
  src/libraries/JsmnSolLib.sol
  src/validators/SessionKeyValidator.sol
  src/validators/WebAuthValidator.sol
Labels: good first issue, project: contracts

#236 fix: Unreachable JSON parsing functions
  src/libraries/JsmnSolLib.sol
Labels: good first issue, project: contracts

#229 feat: use static salt for deploy task
  scripts/deploy.ts
  test/utils.ts
Labels: enhancement

#231 Passkey tests
  src/test/VerifierCaller.sol
  src/validators/WebAuthValidator.sol
  test/PasskeyModule.ts
Labels: enhancement, help wanted, project: contracts

#237 chore: update hex codes
  src/libraries/JsmnSolLib.sol
Labels: good first issue, project: contracts

#250 feat: replace linked lists with enumerable sets
  src/SsoAccount.sol
  src/handlers/ERC1271Handler.sol
  src/handlers/ValidationHandler.sol
  src/libraries/LinkedList.sol
  src/libraries/SsoStorage.sol
  src/managers/HookManager.sol
  src/managers/OwnerManager.sol
  src/managers/ValidatorManager.sol
  test/JsmnSolLib.ts
  test/SessionKeyTest.ts
Labels: enhancement, project: contracts

#238 Update module install and remove interfaces
  package.json
  pnpm-lock.yaml
  src/SsoAccount.sol
  src/interfaces/IHook.sol
  src/interfaces/IHookManager.sol
  src/interfaces/IInitable.sol
  src/interfaces/IModule.sol
  src/interfaces/IModuleValidator.sol
  src/interfaces/IValidatorManager.sol
  src/managers/HookManager.sol
  src/managers/ValidatorManager.sol
  src/validators/SessionKeyValidator.sol
  src/validators/WebAuthValidator.sol
  test/PasskeyModule.ts
  test/SessionKeyTest.ts
  test/utils.ts
Labels: project: contracts

#254 Passkey Account Test
  test/PasskeyModule.ts
Labels: enhancement

#262 chore: add SPDX to IModule.sol
  src/interfaces/IModule.sol
Labels: documentation
