Repository matter-labs/zksync-sso-clave-contracts, pull requests merged in 2025-02, with the labels that each got.

#267 chore: move imports to different packages
  src/AAFactory.sol
  src/SsoAccount.sol
  src/test/ExampleAuthServerPaymaster.sol
  src/test/TestPaymaster.sol
Labels: project: sdk

#269 Fixes of the early results from the second OZ audit
  src/SsoAccount.sol
  src/interfaces/IHookManager.sol
  src/interfaces/IOwnerManager.sol
  src/interfaces/ISsoAccount.sol
  src/libraries/SessionLib.sol
  src/libraries/SsoStorage.sol
  src/managers/HookManager.sol
  src/managers/OwnerManager.sol
  src/managers/ValidatorManager.sol
Labels: project: contracts

#271 feat: Slither pipeline integration
  .github/workflows/slither.yml
  slither.config.json
  src/AAFactory.sol
  src/SsoAccount.sol
  src/managers/HookManager.sol
  src/managers/ValidatorManager.sol
Labels: project: contracts, infra

#290 docs: minor comment improvements
  src/AAFactory.sol
  src/validators/SessionKeyValidator.sol
  src/validators/WebAuthValidator.sol
Labels: security

#285 chore: add more comments to webauthn verify
  src/test/TestWebAuthValidator.sol
  src/validators/WebAuthValidator.sol
  test/PasskeyModule.ts
Labels: security

#288 chore: update authors on contracts
  src/interfaces/IHook.sol
  src/managers/HookManager.sol
Labels: documentation, security

#287 chore: make comments more exact when referring to internal data
  src/AAFactory.sol
  src/interfaces/IOwnerManager.sol
  src/managers/HookManager.sol
  src/managers/OwnerManager.sol
Labels: documentation, security

#294 fix: gas optimizations and minor improvements
  src/libraries/SsoStorage.sol
  src/validators/SessionKeyValidator.sol
  src/validators/WebAuthValidator.sol
Labels: security

#293 fix: batch caller improvements
  src/batch/BatchCaller.sol
  src/libraries/Errors.sol
Labels: security

#295 feat: change salt depending on deployer
  src/AAFactory.sol
  test/BasicTest.ts
Labels: security

#312 feat: remove standalone precompile test
  src/test/TestWebAuthValidator.sol
  src/validators/WebAuthValidator.sol
  test/PasskeyModule.ts
Labels: documentation, security

#310 chore: update r and s casting to 0
  src/validators/WebAuthValidator.sol
Labels: project: contracts, security
