Repository matter-labs/zksync-sso-clave-contracts, pull requests merged in 2025-04, with the labels that each got.

#333 WebAuthN Audit Changes
  src/helpers/VerifierCaller.sol
  src/libraries/Errors.sol
  src/validators/WebAuthValidator.sol
  test/PasskeyModule.ts
Labels: security

#369 Assorted audit request changes
  src/SsoAccount.sol
  src/libraries/SsoStorage.sol
  src/managers/HookManager.sol
  src/managers/ValidatorManager.sol
  src/validators/WebAuthValidator.sol
Labels: security

#377 Audit (N-02): unused SSO var
  src/SsoAccount.sol
Labels: security

#378 Audit (N-013): minor gas optimization
  src/validators/WebAuthValidator.sol
Labels: security

#353 Audit (N-09): use guardian related names instead of validationKey
  src/interfaces/IGuardianRecoveryValidator.sol
  src/test/ExampleAuthServerPaymaster.sol
  src/validators/GuardianRecoveryValidator.sol
  test/GuardianRecoveryValidatorTest.ts
Labels: security

#350 Audit (N-02): remove unused code (errors)
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#346 Audit (L-03): pendingRecoveryData does not need to be public
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#355 Audit (N-12): add security contact
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#359 Audit (N-15): use more limiting visibility specifier
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#356 Audit (N-13): use prefix increment operator for gas optimization
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#349 Audit (L-06): add zero address checks
  src/validators/GuardianRecoveryValidator.sol
  test/GuardianRecoveryValidatorTest.ts
Labels: security

#379 Audit (M-03): overwrite recovery process
  src/validators/GuardianRecoveryValidator.sol
  test/GuardianRecoveryValidatorTest.ts
Labels: security

#351 Audit (N-07): use safeCastToAddress in GuardianRecoveryValidator
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#358 Audit (N-11): use named parameters in mappings
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#354 Audit (N-10): use custom error instead of string revert
  src/validators/GuardianRecoveryValidator.sol
  test/GuardianRecoveryValidatorTest.ts
Labels: security

#362 Audit (N-14): unify methods ordering
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#361 fix(N-05,N-06): make interface consistent with implementation
  src/interfaces/IGuardianRecoveryValidator.sol
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#347 Audit (L-05): store accounts hashed origin domains
  src/interfaces/IGuardianRecoveryValidator.sol
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#345 Audit (M-06): fix pending guardian blocking unInstall method
  src/validators/GuardianRecoveryValidator.sol
  test/GuardianRecoveryValidatorTest.ts
Labels: security

#380 Audit (L-10): missing documentation
  src/interfaces/IGuardianRecoveryValidator.sol
  src/validators/GuardianRecoveryValidator.sol
Labels: security

#398 feat: audited guardian recovery
  package.json
  pnpm-lock.yaml
  scripts/deploy.ts
  src/AAFactory.sol
  src/SsoAccount.sol
  src/TransparentProxy.sol
  src/helpers/VerifierCaller.sol
  src/interfaces/IGuardianRecoveryValidator.sol
  src/interfaces/IHookManager.sol
  src/libraries/Errors.sol
  src/test/ExampleAuthServerPaymaster.sol
  src/validators/GuardianRecoveryValidator.sol
  src/validators/WebAuthValidator.sol
  test/BasicTest.ts
  test/GuardianRecoveryValidatorTest.ts
  test/PasskeyModule.ts
  test/SessionKeyTest.ts
  test/utils.ts
Labels: enhancement, project: contracts

#391 fix: simplify ERC1271 validation
  src/handlers/ERC1271Handler.sol
Labels: enhancement

#437 feat: upgrade zksolc
  hardhat.config.ts
Labels: project: contracts

#443 feat: perform deploy as part of upgrade
  README.md
  scripts/deploy.ts
  scripts/upgrade.ts
  test/utils.ts
Labels: documentation, enhancement

#399 N-01 Using uint8 for Constants Is More Expensive Than uint256
  src/OidcKeyRegistry.sol
  src/validators/OidcRecoveryValidator.sol
Labels: security

#400 N-02 Inconsistent License in OidcKeyRegistry.sol
  src/OidcKeyRegistry.sol
  src/validators/OidcRecoveryValidator.sol
Labels: security

#401 N-03 Redundant Local Variable in _validateModulus
  src/OidcKeyRegistry.sol
Labels: security

#402 N-04 Use of uint Instead of uint256
  src/validators/OidcRecoveryValidator.sol
Labels: security

#403 N-05 Magic Numbers in the Code
  src/validators/OidcRecoveryValidator.sol
Labels: security

#404 N-06 Use Custom Errors
  src/validators/OidcRecoveryValidator.sol
Labels: security

#410 N-12 Refactor and Improvement Opportunities
  src/OidcKeyRegistry.sol
  src/interfaces/IOidcKeyRegistry.sol
  src/interfaces/IOidcRecoveryValidator.sol
  src/interfaces/IZkVerifier.sol
  src/validators/OidcRecoveryValidator.sol
  test/OidcRecoveryValidatorTest.ts
Labels: security

#422 L-04 Potential Loss of Ownership During Transfer
  src/OidcKeyRegistry.sol
Labels: security

#411 N-13 Unnecessary override Keyword in onInstall and onUninstall
  src/validators/OidcRecoveryValidator.sol
Labels: security

#428 L-12 OidcRecoveryValidator Does Not Follow the ERC-1271 Flow
  src/validators/OidcRecoveryValidator.sol
  test/OidcRecoveryValidatorTest.ts
Labels: security

#435 N-09 Circular Buffer Initialization Causes Counterintuitive Key Indexing
  src/OidcKeyRegistry.sol
  test/OidcKeyRegistryTest.ts
Labels: security

#427 L-11 Insufficient Validation of iss Argument Length in addOidcAccount
  src/interfaces/IOidcRecoveryValidator.sol
  src/validators/OidcRecoveryValidator.sol
  test/OidcKeyRegistryTest.ts
  test/OidcRecoveryValidatorTest.ts
Labels: security

#431 M-03 Unauthorized Control via Manipulated pendingPasskeyHash in startRecovery Process
  src/validators/OidcRecoveryValidator.sol
Labels: security

#430 M-02 Insufficient Validation of RSA Modulus and Exponent in _validateKeyBatch
  src/OidcKeyRegistry.sol
  src/interfaces/IOidcKeyRegistry.sol
  src/validators/OidcRecoveryValidator.sol
  test/OidcKeyRegistryTest.ts
Labels: security

#432 L-01 Duplicate kid Values in OidcKeyRegistry Allow for Partial Key Deletion and Retrieval
  src/OidcKeyRegistry.sol
  src/interfaces/IOidcKeyRegistry.sol
  test/OidcKeyRegistryTest.ts
Labels: security

#434 N-08 State Variable Visibility Not Explicitly Declared
  src/OidcKeyRegistry.sol
  src/interfaces/IOidcKeyRegistry.sol
  src/interfaces/IOidcRecoveryValidator.sol
  src/interfaces/IZkVerifier.sol
  src/validators/OidcRecoveryValidator.sol
  test/OidcKeyRegistryTest.ts
  test/OidcRecoveryValidatorTest.ts
Labels: security

#442 N-15 improve comments regarding OIDC pubkeys
  src/validators/OidcRecoveryValidator.sol
  test/OidcKeyRegistryTest.ts
Labels: security

#436 N-14 Endianness Mismatch in senderHash Representation Between Contract and Circuit
  src/OidcKeyRegistry.sol
  src/interfaces/IOidcRecoveryValidator.sol
  src/validators/OidcRecoveryValidator.sol
  test/OidcKeyRegistryTest.ts
  test/OidcRecoveryValidatorTest.ts
Labels: security
